spring.application.name=NauJava
spring.messages.encoding=UTF-8

# management.endpoints.jmx.exposure.include=*
management.endpoints.web.exposure.include=*

app.version=1.0.0
app.name=Password Generator
