spring:
  application:
    name: NauJava

  main:
    allow-bean-definition-overriding: true

  messages:
    encoding: UTF-8

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        highlight_sql: true
        hbm2ddl:
          auto: update
  data:
    rest:
      base-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  name: "Password Generator"
  version: "1.0.1"
  time:
    formatter: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
  message:
    name: "%s  INFO Текущее название приложения: %s\n"
    version: "%s  INFO Текущая версия приложения: %s\n"

